kind: PersistentVolume
apiVersion: v1
metadata:
  name: bitbucket-pv-volume
  labels:
    type: local
    app: bitbucket
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/kube-data/bitbucket"
    type: Directory
