apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - name: jenkins-http
    port: 8080
    targetPort: jenkins-http
  - name: jenkins-ssh
    port: 22
    targetPort: jenkins-ssh
  type: NodePort
