apiVersion: v1
kind: Service
metadata:
  labels:
    app: daas-ui
  name: daas-ui
spec:
  ports:
  - nodePort: 30664
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: daas-ui
  type: NodePort