kind: PersistentVolume
apiVersion: v1
metadata:
  name: registry-pv-volume
  labels:
    type: local
    app: registry
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/kube-data/registry"
    type: Directory
