apiVersion: apps/v1
kind: Deployment
metadata:
  name: daas-api
  labels:
    app: daas-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: daas-api
  template:
    metadata:
      labels:
        app: daas-api
    spec:
      containers:
      - name: daas-api
        image: amitmazor/daas-api:2
        ports:
        - containerPort: 5001