apiVersion: v1
kind: Service
metadata:
  labels:
    app: daas-api
  name: daas-api
spec:
  ports:
  - nodePort: 30123
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: daas-api
  type: NodePort
